-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               12.1.2-MariaDB - MariaDB Server
-- Server OS:                    Win64
-- HeidiSQL Version:             12.14.0.7165
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table realfey_illusion_spells_db.spells
CREATE TABLE IF NOT EXISTS `spells` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `spell_name` varchar(255) NOT NULL,
  `archive_URL` varchar(500) DEFAULT NULL,
  `rank` int(11) NOT NULL,
  `traits` text DEFAULT NULL,
  `actions` varchar(512) DEFAULT NULL,
  `rarity` varchar(100) DEFAULT NULL,
  `spell_target` varchar(512) DEFAULT NULL,
  `spell_range` varchar(100) DEFAULT NULL,
  `area` varchar(100) DEFAULT NULL,
  `duration` varchar(255) DEFAULT NULL,
  `defense` varchar(512) DEFAULT NULL,
  `heighten` varchar(255) DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `spoilers` varchar(512) DEFAULT NULL,
  `source` varchar(512) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=75 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- Dumping data for table realfey_illusion_spells_db.spells: ~74 rows (approximately)
INSERT INTO `spells` (`id`, `spell_name`, `archive_URL`, `rank`, `traits`, `actions`, `rarity`, `spell_target`, `spell_range`, `area`, `duration`, `defense`, `heighten`, `summary`, `spoilers`, `source`) VALUES
	(1, 'Aura of the Unremarkable', 'https://2e.aonprd.com/Spells.aspx?ID=847', 6, 'Illusion, Mental, Uncommon', 'Two Actions', 'Uncommon', '', '', '30-foot emanation', 'sustained up to 1 minute', '', '', 'You and allies in the area appear to be completely innocuous to other creatures within the spell\'s area, regardless of the actions you\'re committing.', 'Fists of the Ruby Phoenix', 'Pathfinder #166: Despair on Danger Island pg. 77'),
	(2, 'Befitting Attire', 'https://2e.aonprd.com/Spells.aspx?ID=867', 2, 'Illusion, Visual', 'Two Actions', 'Common', '5 willing creatures', '30 feet', '', '1 hour', '', '4th, 5th', 'Make clothes fit the occasion.', '', 'Secrets of Magic pg. 90 2.0'),
	(3, 'Blanket of Stars', 'https://2e.aonprd.com/Spells.aspx?ID=1967', 6, 'Concentrate, Illusion, Manipulate', 'Two Actions', 'Common', '', '', '', '10 minutes', 'Will', '', 'A cloak of darkness hides you in the dark.', '', 'Player Core 2 pg. 241 1.1'),
	(4, 'Blind Eye', 'https://2e.aonprd.com/Spells.aspx?ID=1213', 5, 'Illusion, Uncommon', '1 minute', 'Uncommon', '1 object', 'touch', '', 'until the next time you make your daily preparations', '', '', 'You enchant a single object, preventing it from being used for magical observation.', 'Blood Lords', 'Pathfinder #182: Graveclaw pg. 78'),
	(5, 'Blur', 'https://2e.aonprd.com/Spells.aspx?ID=28', 2, 'Concentrate, Illusion, Manipulate, Visual', 'Two Actions', 'Common', '1 creature', 'touch', '', '1 minute', '', '', 'Target\'s form becomes blurry and hard to hit.', '', 'Player Core pg. 318 2.0'),
	(6, 'Boots on the Ground', 'https://2e.aonprd.com/Spells.aspx?ID=2495', 6, 'Auditory, Concentrate, Illusion, Manipulate, Visual', 'Three Actions', 'Common', '', '100 feet', '', 'until you next make your next daily preparations', 'Will', '8th', 'You craft the illusion of your army being much bigger than it actually is, hoping to overwhelm the opposing forces and shatter their hopes.', '', 'Battlecry! pg. 84'),
	(7, 'Bullhorn', 'https://2e.aonprd.com/Spells.aspx?ID=1971', 0, 'Auditory, Cantrip, Concentrate, Illusion, Manipulate', 'Two Actions', 'Common', '', '', '', '10 minutes', '', '5th, 7th', 'Magnify your voice to be heard at a distance.', '', 'Player Core 2 pg. 241 1.1'),
	(8, 'Burglar\'s Blind', 'https://2e.aonprd.com/Spells.aspx?ID=2336', 3, 'Illusion, Manipulate, Rare, Subtle', 'Two Actions', 'Rare', '1 willing creature', '60 feet', '', 'sustained up to 10 minutes', '', '5th', 'The only thing thieves love more than being silent and stealthy is the piles of gold they win with that silence and stealth.', '', 'NPC Core pg. 26'),
	(9, 'Chromatic Image', 'https://2e.aonprd.com/Spells.aspx?ID=882', 6, 'Illusion, Visual', 'Two Actions', 'Common', '', '', '', '1 minute', '', '', 'Colorful mirror images damage foes who destroy them.', '', 'Secrets of Magic pg. 95 2.0'),
	(10, 'Disguise Magic', 'https://2e.aonprd.com/Spells.aspx?ID=1491', 1, 'Concentrate, Illusion, Manipulate', '1 minute', 'Common', '1 item or spell effect', '30 feet', '', 'until your next daily preparations', '', '2nd', 'Mask the aura of a spell or item.', '', 'Player Core pg. 324 2.0'),
	(11, 'Distracting Chatter', 'https://2e.aonprd.com/Spells.aspx?ID=895', 3, 'Auditory, Illusion', 'Two Actions', 'Common', '1 creature', '30 feet', '', 'varies', 'Will', '7th', 'Distract a creature with auditory illusions.', '', 'Secrets of Magic pg. 100 2.0'),
	(12, 'Dizzying Colors', 'https://2e.aonprd.com/Spells.aspx?ID=1500', 1, 'Concentrate, Illusion, Incapacitation, Manipulate, Visual', 'Two Actions', 'Common', '', '', '15-foot cone', '1 or more rounds (see below)', 'Will', '', 'Swirling colors blind, dazzle, or stun creatures.', '', 'Player Core pg. 326 2.0'),
	(13, 'Embed Message', 'https://2e.aonprd.com/Spells.aspx?ID=1511', 2, 'Concentrate, Illusion, Manipulate', 'Two Actions', 'Common', '1 object or willing creature', 'touch', '', 'unlimited', '', '4th, 6th', 'Leave an illusory message to be triggered at a later date.', '', 'Player Core pg. 328 2.0'),
	(14, 'Empty Pack', 'https://2e.aonprd.com/Spells.aspx?ID=1151', 2, 'Illusion', 'Two Actions', 'Common', '1 container of 2 Bulk or less', 'touch', '', '1 hour', '', '4th', 'Make objects inside a container invisible', '', 'Dark Archive pg. 105'),
	(15, 'Exchange Image', 'https://2e.aonprd.com/Spells.aspx?ID=549', 1, 'Illusion, Uncommon, Visual', 'Two Actions', 'Uncommon', 'you and 1 other humanoid', 'touch', '', 'varies', 'Will', '', 'Trade appearances with the target.', 'Age of Ashes', 'Pathfinder #147: Tomorrow Must Burn pg. 73'),
	(16, 'Fallen Soldier\'s Lament', 'https://2e.aonprd.com/Spells.aspx?ID=2503', 4, 'Concentrate, Illusion, Manipulate, Mental, Rare, Visual', 'Two Actions', 'Rare', '1 corpse of a Medium or smaller creature that has died within the past 8 hours', '100 feet', '', 'sustained up to 1 minute', 'Will', '6th', 'You raise an illusion in the space of a fallen foe, crafting it to resemble a ghost of your target before parading it across the battlefield.', '', 'Battlecry! pg. 86'),
	(17, 'False Nature', 'https://2e.aonprd.com/Spells.aspx?ID=1148', 4, 'Illusion, Uncommon', 'Three Actions', 'Uncommon', 'one unattended item or one item you\'re holding', 'touch', '', 'until your next daily preparations', '', '', 'Rewrite perception and memory to make one object appear to be another', '', 'Dark Archive pg. 93'),
	(18, 'False Vision', 'https://2e.aonprd.com/Spells.aspx?ID=90', 5, 'Concentrate, Illusion, Manipulate, Uncommon', '10 minutes', 'Uncommon', '', 'touch', '100-foot burst', 'until your next daily preparations', '', '', 'Trick a scrying spell.', '', 'Player Core pg. 330 2.0'),
	(19, 'Falsify Heat', 'https://2e.aonprd.com/Spells.aspx?ID=1353', 2, 'Concentrate, Fire, Illusion, Manipulate', 'Two Actions', 'Common', '1 willing creature or object', '60 feet', '', '8 hours', '', '4th', 'Make a creature\'s body heat seem different.', '', 'Rage of Elements pg. 119 2.0'),
	(20, 'Figment', 'https://2e.aonprd.com/Spells.aspx?ID=1528', 0, 'Cantrip, Concentrate, Illusion, Manipulate, Subtle', 'Two Actions', 'Common', '', '30 feet', '', 'sustained', '', '', 'Create a simple auditory or visual illusion.', '', 'Player Core pg. 331 2.0'),
	(21, 'Flashy Disappearance', 'https://2e.aonprd.com/Spells.aspx?ID=1285', 1, 'Illusion, Uncommon', 'Two Actions', 'Uncommon', '', '', '', '', '', '', 'You create a puff of colorful smoke that quickly disperses while you become temporarily invisible.', '', 'Firebrands pg. 89 2.0'),
	(22, 'Hallucination', 'https://2e.aonprd.com/Spells.aspx?ID=1551', 5, 'Illusion, Incapacitation, Manipulate, Mental, Subtle', 'Two Actions', 'Common', '1 creature', '30 feet', '', '1 hour', '', '6th, 8th', 'Cause a creature to believe one thing is another, to notice something that isn\'t there, or to be unable to detect something.', '', 'Player Core pg. 334 2.0'),
	(23, 'Hypnotize', 'https://2e.aonprd.com/Spells.aspx?ID=1564', 3, 'Illusion, Manipulate, Subtle, Visual', 'Two Actions', 'Common', '', '120 feet', '10-foot burst', 'sustained up to 1 minute', 'Will', '', 'Shifting colors dazzle and fascinate creatures.', '', 'Player Core pg. 336 2.0'),
	(24, 'Illusory Creature', 'https://2e.aonprd.com/Spells.aspx?ID=1567', 2, 'Auditory, Concentrate, Illusion, Manipulate, Olfactory, Visual', 'Two Actions', 'Common', '', '500 feet', '', 'sustained', '', '1', 'Form a convincing illusion of a creature.', '', 'Player Core pg. 336 2.0'),
	(25, 'Illusory Disguise', 'https://2e.aonprd.com/Spells.aspx?ID=1568', 1, 'Concentrate, Illusion, Manipulate, Visual', 'Two Actions', 'Common', '1 willing creature', '30 feet', '', '1 hour', '', '3rd, 4th, 7th', 'Make yourself look like a different creature.', '', 'Player Core pg. 337 2.0'),
	(26, 'Illusory Object', 'https://2e.aonprd.com/Spells.aspx?ID=1569', 1, 'Concentrate, Illusion, Manipulate, Visual', 'Two Actions', 'Common', '', '500 feet', '20-foot burst', '10 minutes', '', '2nd, 5th', 'Form a convincing illusion of an object.', '', 'Player Core pg. 337 2.0'),
	(27, 'Illusory Scene', 'https://2e.aonprd.com/Spells.aspx?ID=1570', 5, 'Auditory, Concentrate, Illusion, Manipulate, Olfactory, Visual', '10 minutes', 'Common', '', '500 feet', '30-foot burst', '1 hour', '', '6th, 8th', 'Create an imaginary scene containing multiple creatures and objects.', '', 'Player Core pg. 337 2.0'),
	(28, 'Illusory Shroud', 'https://2e.aonprd.com/Spells.aspx?ID=1287', 2, 'Illusion, Uncommon, Visual', 'Two Actions', 'Uncommon', '1 willing creature', 'touch', '', '1 minute', '', '', 'You shroud the target in subtle illusions that make it difficult to detect.', '', 'Firebrands pg. 89 2.0'),
	(29, 'Instant Minefield', 'https://2e.aonprd.com/Spells.aspx?ID=2509', 5, 'Fire, Illusion, Manipulate, Subtle', 'Three Actions', 'Common', '', '100 feet', '', '10 minutes', '', '1', 'You create several hidden mines throughout the area that explode when stepped on.', '', 'Battlecry! pg. 88'),
	(30, 'Instant Parade', 'https://2e.aonprd.com/Spells.aspx?ID=1288', 3, 'Auditory, Aura, Illusion, Uncommon, Visual', 'Two Actions', 'Uncommon', '', '', '10-foot emanation', '10 minutes', '', '', 'An illusory parade with dozens of participants and performers appears around you, following you as you move.', '', 'Firebrands pg. 89 2.0'),
	(31, 'Invisibility', 'https://2e.aonprd.com/Spells.aspx?ID=164', 2, 'Illusion, Manipulate, Subtle', 'Two Actions', 'Common', '1 creature', 'touch', '', '10 minutes', '', '4th', 'A creature can\'t be seen until it attacks.', '', 'Player Core pg. 339 2.0'),
	(32, 'Invisibility Curtain', 'https://2e.aonprd.com/Spells.aspx?ID=936', 4, 'Illusion', 'Three Actions', 'Common', '', '120 feet', '', 'sustained', '', '7th', 'Wall makes creatures on one side invisible to the other side.', '', 'Secrets of Magic pg. 112 2.0'),
	(33, 'Invisible Item', 'https://2e.aonprd.com/Spells.aspx?ID=700', 1, 'Concentrate, Illusion, Manipulate', 'Two Actions', 'Common', '1 object', 'touch', '', '1 hour', '', '3rd, 7th', 'Make an item disappear.', '', 'Player Core 2 pg. 247 1.1'),
	(34, 'Item Facade', 'https://2e.aonprd.com/Spells.aspx?ID=166', 1, 'Concentrate, Illusion, Manipulate, Visual', 'Two Actions', 'Common', '1 object no more than 10 feet by 10 feet by 10 feet', 'touch', '', '1 hour', '', '2nd, 3rd', 'Disguise an item to look perfect or shoddy.', '', 'Player Core pg. 340 2.0'),
	(35, 'Mask of Terror', 'https://2e.aonprd.com/Spells.aspx?ID=1595', 7, 'Concentrate, Emotion, Fear, Illusion, Manipulate, Mental, Visual', 'Two Actions', 'Common', '1 creature', '30 feet', '', '1 minute', '', '8th', 'A creature\'s fearsome illusory appearance frightens observers.', '', 'Player Core pg. 342 2.0'),
	(36, 'Message', 'https://2e.aonprd.com/Spells.aspx?ID=1598', 0, 'Auditory, Cantrip, Concentrate, Illusion, Linguistic, Mental, Subtle', 'Single Action', 'Common', '1 creature', '120 feet', '', 'see below', '', '3rd', 'Speak a message to a distant creature, who can reply.', '', 'Player Core pg. 343 2.0'),
	(37, 'Mirage', 'https://2e.aonprd.com/Spells.aspx?ID=1604', 4, 'Concentrate, Illusion, Manipulate, Uncommon', '10 minutes', 'Uncommon', '', '500 feet', '50-foot burst', 'until your next daily preparations', '', '5th', 'Disguise one natural environment as another.', '', 'Player Core pg. 344 2.0'),
	(38, 'Mirror Image', 'https://2e.aonprd.com/Spells.aspx?ID=197', 2, 'Illusion, Visual', 'Two Actions', 'Common', '', '', '', '1 minute', '', '', 'Illusory duplicates of you cause attacks to miss.', '', 'Core Rulebook pg. 352 4.0'),
	(39, 'Mirror Malefactors', 'https://2e.aonprd.com/Spells.aspx?ID=950', 5, 'Illusion, Mental, Visual', 'Two Actions', 'Common', '1 creature', '30 feet', '', 'sustained up to 1 minute', 'basic Will', '1', 'Mirrors surround a target, and the reflections attack them repeatedly.', '', 'Secrets of Magic pg. 116 2.0'),
	(40, 'Mirror\'s Misfortune', 'https://2e.aonprd.com/Spells.aspx?ID=951', 4, 'Illusion', 'Two Actions', 'Common', '', '', '', '1 minute', '', '', 'Split into two copies. Destroying the fake curses the attacker.', '', 'Secrets of Magic pg. 117 2.0'),
	(41, 'Misdirection', 'https://2e.aonprd.com/Spells.aspx?ID=198', 2, 'Illusion', '1 minute', 'Common', '2 creatures or objects', '30 feet', '', 'until the next time you make your daily preparations', '', '', 'Cause one creature\'s auras to appear to be another\'s.', '', 'Core Rulebook pg. 352 4.0'),
	(42, 'Mislead', 'https://2e.aonprd.com/Spells.aspx?ID=1605', 6, 'Concentrate, Illusion, Manipulate', 'Two Actions', 'Common', '', '', '', 'sustained up to 1 minute', '', '', 'Turn invisible and create a duplicate of yourself who acts like you.', '', 'Player Core pg. 344 2.0'),
	(43, 'Musical Accompaniment', 'https://2e.aonprd.com/Spells.aspx?ID=1289', 0, 'Auditory, Cantrip, Illusion', 'Two Actions', 'Common', '', '', '', '1 minute', '', '2nd', 'You\'re surrounded by orchestral music that shifts and changes to match your behavior.', '', 'Firebrands pg. 90 2.0'),
	(44, 'Nightmare', 'https://2e.aonprd.com/Monsters.aspx?ID=3105', 4, 'Concentrate, Illusion, Manipulate, Mental', '10 minutes', 'Common', '1 creature you know by name', 'planetary', '', '1 day', 'Will', '', 'Plague a creature\'s dreams with disturbing nightmares.', '', 'Player Core pg. 346 2.0'),
	(45, 'Ocular Overload', 'https://2e.aonprd.com/Spells.aspx?ID=959', 4, 'Contingency, Illusion, Incapacitation, Visual', '10 minutes', 'Common', '', '', '', '24 hours', '', '', 'Set a contingency to interfere with the vision of a creature attacking you.', '', 'Secrets of Magic pg. 118 2.0'),
	(46, 'Oneiric Mire', 'https://2e.aonprd.com/Spells.aspx?ID=961', 3, 'Illusion, Mental, Visual', 'Three Actions', 'Common', '', '120 feet', '20-foot burst', '1 minute', '', '', 'Create illusory quicksand that tricks creatures into thinking they\'re stuck.', '', 'Secrets of Magic pg. 119 2.0'),
	(47, 'Paranoia', 'https://2e.aonprd.com/Spells.aspx?ID=1623', 2, 'Concentrate, Illusion, Manipulate, Mental', 'Two Actions', 'Common', '1 creature', '30 feet', '', '1 minute', 'Will', '6th', 'Make a creature believe everyone is a threat.', '', 'Player Core pg. 348 2.0'),
	(48, 'Phantasmal Calamity', 'https://2e.aonprd.com/Spells.aspx?ID=1630', 6, 'Concentrate, Illusion, Manipulate, Mental', 'Two Actions', 'Common', '', '500 feet', '30-foot burst', '', 'Will', '1', 'Create visions of an apocalypse to damage creatures mentally.', '', 'Player Core pg. 349 2.0'),
	(49, 'Phantasmal Protagonist', 'https://2e.aonprd.com/Spells.aspx?ID=1230', 4, 'Illusion, Mental, Rare', 'Three Actions', 'Rare', '', '30 feet', '', 'sustained up to 1 minute', '', '1', 'You create a phantasmal incarnation of a significant character from a novel, historical work, or religious parable.', 'Kingmaker', 'Kingmaker Companion Guide pg. 46'),
	(50, 'Phantasmal Treasure', 'https://2e.aonprd.com/Spells.aspx?ID=707', 2, 'Concentrate, Emotion, Illusion, Manipulate, Mental', 'Two Actions', 'Common', '1 living creature', '60 feet', '', 'varies', 'Will', '', 'Tempt a creature with an illusory reward.', '', 'Player Core 2 pg. 249 1.1'),
	(51, 'Phantom Crowd', 'https://2e.aonprd.com/Spells.aspx?ID=968', 2, 'Illusion, Visual', 'Two Actions', 'Common', '', '60 feet', 'a 10-foot square', 'sustained up to 10 minutes', '', '1', 'Create an illusory crowd that loudly agrees with you.', '', 'Secrets of Magic pg. 121 2.0'),
	(52, 'Phantom Pain', 'https://2e.aonprd.com/Spells.aspx?ID=1632', 1, 'Concentrate, Illusion, Manipulate, Mental, Nonlethal', 'Two Actions', 'Common', '1 creature', '30 feet', '', '1 minute', 'Will', '1', 'Cause a creature ongoing pain that sickens it.', '', 'Player Core pg. 349 2.0'),
	(53, 'Phantom Prison', 'https://2e.aonprd.com/Spells.aspx?ID=969', 3, 'Illusion, Incapacitation, Mental, Visual', 'Three Actions', 'Common', '1 creature', '50 feet', '', '1 minute', 'Will', '8th', 'Trap a creature in illusory walls until it disbelieves.', '', 'Secrets of Magic pg. 121 2.0'),
	(54, 'Portrait of the Artist', 'https://2e.aonprd.com/Spells.aspx?ID=971', 5, 'Illusion, Visual', '1 minute', 'Common', '', '', '', '1 hour', '', '', 'Appear to have the features and skills of a famous artist.', '', 'Secrets of Magic pg. 122 2.0'),
	(55, 'Project Image', 'https://2e.aonprd.com/Spells.aspx?ID=1640', 7, 'Concentrate, Illusion, Manipulate, Mental', 'Two Actions', 'Common', '', '30 feet', '', 'sustained up to 1 minute', '', '2', 'Make an illusion of yourself you can cast spells through.', '', 'Player Core pg. 351 2.0'),
	(56, 'Rallying Banner', 'https://2e.aonprd.com/Spells.aspx?ID=1293', 5, 'Auditory, Illusion, Uncommon, Visual', 'Two Actions', 'Uncommon', '1 willing creature', '30 feet', '', '1 minute', '', '', 'You create an illusory banner representing a revolution, social movement, or organization such as the Firebrands.', '', 'Firebrands pg. 90 2.0'),
	(57, 'Reflected Beauty', 'https://2e.aonprd.com/Spells.aspx?ID=2448', 4, 'Concentrate, Illusion, Manipulate, Uncommon, Visual', 'Two Actions', 'Uncommon', '', '', '', '1 hour', '', '', 'When you cast reflected beauty, choose a willing creature that is the same size as you and that you can see within 30 feet.', 'Curtain Call', 'Pathfinder #205: Singer, Stalker, Skinsaw Man pg. 81'),
	(58, 'Replicate', 'https://2e.aonprd.com/Feats.aspx?ID=3799', 4, 'Illusion, Shadow', 'Three Actions', 'Common', '1 willing or unconscious creature of 8th level or lower', '60 feet', '', 'sustained', '', '1', 'Create an illusory duplicate of a creature.', '', 'Secrets of Magic pg. 125 2.0'),
	(59, 'Sculpt Sound', 'https://2e.aonprd.com/Spells.aspx?ID=714', 3, 'Illusion', 'Two Actions', 'Common', '1 creature or object', 'touch', '', '10 minutes', '', '5th', 'Quiet or alter the sound from a creature or object.', '', 'Advanced Player\'s Guide pg. 224 2.0'),
	(60, 'Secret Page', 'https://2e.aonprd.com/Spells.aspx?ID=270', 3, 'Illusion, Visual', '1 minute', 'Common', '1 page up to 3 square feet in size', 'touch', '', 'unlimited', '', '', 'Alter the appearance of a page.', '', 'Core Rulebook pg. 367 4.0'),
	(61, 'Shadow Raid', 'https://2e.aonprd.com/Spells.aspx?ID=996', 7, 'Illusion, Shadow', 'Three Actions', 'Common', '', '120 feet', '30-foot burst', '1 minute', 'basic Reflex or Will (target\'s choice)', '9th', 'A swarm of illusory shadows damages foes in the area and provides concealment.', '', 'Secrets of Magic pg. 129 2.0'),
	(62, 'Shared Invisibility', 'https://2e.aonprd.com/Spells.aspx?ID=2025', 3, 'Aura, Illusion, Manipulate, Subtle', 'Two Actions', 'Common', 'you and up to 5 willing creatures', '', '30-foot emanation', '10 minutes', '', '5th', 'You and nearby creatures become invisible.', '', 'Player Core 2 pg. 251 1.1'),
	(63, 'Shock and Awe', 'https://2e.aonprd.com/Spells.aspx?ID=2513', 5, 'Auditory, Concentrate, Emotion, Fear, Illusion, Manipulate, Mental, Visual', 'Three Actions', 'Common', '', '100 feet', '50-foot burst', '1 round', 'Will', '', 'You create the illusion of cannons exploding, bullets and arrows flying, and magical ballistics firing, as an overwhelming torrent of information, both visual and auditory.', '', 'Battlecry! pg. 89'),
	(64, 'Silence', 'https://2e.aonprd.com/Spells.aspx?ID=1674', 2, 'Illusion, Manipulate, Subtle', 'Two Actions', 'Common', '1 willing creature', 'touch', '', '1 minute', '', '4th', 'Mute all sound from a willing creature.', '', 'Player Core pg. 357 2.0'),
	(65, 'Strange Geometry', 'https://2e.aonprd.com/Spells.aspx?ID=2032', 5, 'Concentrate, Illusion, Manipulate', 'Three Actions', 'Common', '', '60 feet', '4 cubes, each 10 feet on a side', '1 minute', 'Will', '', 'Confoundingly warp spatial geometry, making passage difficult and destinations unpredictable.', '', 'Player Core 2 pg. 252 1.1'),
	(66, 'Teeth to Terror', 'https://2e.aonprd.com/Spells.aspx?ID=1210', 2, 'Fear, Illusion, Mental, Uncommon', 'Two Actions', 'Uncommon', '1 creature with teeth', '30 feet', '', '1 minute', 'Will', '2', 'The target believes its teeth are falling out, crawling along its face, stabbing into its body, and cramming themselves down its throat.', 'Blood Lords', 'Pathfinder #181: Zombie Feast pg. 79'),
	(67, 'Thicket of Knives', 'https://2e.aonprd.com/Spells.aspx?ID=1017', 1, 'Illusion, Visual', 'Two Actions', 'Common', '', '', '', '1 minute', '', '', 'Illusory copies of your weapon arm improve your ability to feint.', '', 'Secrets of Magic pg. 136 2.0'),
	(68, 'Umbral Extraction', 'https://2e.aonprd.com/Spells.aspx?ID=1022', 2, 'Illusion, Mental, Shadow', 'Two Actions', 'Common', '', '', '', '3 rounds', '', '', 'Attempt to steal a spell slot.', '', 'Secrets of Magic pg. 137 2.0'),
	(69, 'Umbral Graft', 'https://2e.aonprd.com/Spells.aspx?ID=1023', 4, 'Illusion, Shadow', 'Two Actions', 'Common', '', '', '', '3 rounds', '', '', 'Attempt to steal an active spell.', '', 'Secrets of Magic pg. 137 2.0'),
	(70, 'Umbral Mindtheft', 'https://2e.aonprd.com/Spells.aspx?ID=1211', 2, 'Illusion, Mental, Shadow, Uncommon', 'Two Actions', 'Uncommon', '', '', '', '3 rounds', '', '', 'You prepare to steal a broad field of knowledge from another creature, siphoning it from their mind and storing it in a pocket of the Shadow Plane connected to your own mind.', 'Blood Lords', 'Pathfinder #181: Zombie Feast pg. 80'),
	(71, 'Ventriloquism', 'https://2e.aonprd.com/Spells.aspx?ID=356', 1, 'Auditory, Concentrate, Illusion, Manipulate', 'Two Actions', 'Common', '', '', '', '10 minutes', '', '2nd', 'Throw your voice.', '', 'Player Core pg. 366 2.0'),
	(72, 'Vibrant Pattern', 'https://2e.aonprd.com/Spells.aspx?ID=1741', 6, 'Illusion, Incapacitation, Manipulate, Subtle, Visual', 'Two Actions', 'Common', '', '120 feet', '10-foot burst', 'sustained up to 1 minute', 'Will', '', 'Make a pattern of lights that dazzle and blinds creatures who enter the area.', '', 'Player Core pg. 366 2.0'),
	(73, 'Vision of Beauty', 'https://2e.aonprd.com/Spells.aspx?ID=1238', 4, 'Emotion, Illusion, Incapacitation, Mental, Rare', 'Two Actions', 'Rare', '1 creature', '60 feet', '', 'varies', 'Will', '2', 'You create a phantasmal image of the most beautiful creature imaginable to the target at a location somewhere within the spell\'s range.', 'Kingmaker', 'Kingmaker Companion Guide pg. 103'),
	(74, 'Visions of Danger', 'https://2e.aonprd.com/Spells.aspx?ID=2040', 7, 'Auditory, Concentrate, Illusion, Manipulate, Visual', 'Three Actions', 'Common', '', '500 feet', '30-foot burst', '1 minute', 'basic Will', '1', 'A vision of a swarm deals mental damage.', '', 'Player Core 2 pg. 254 1.1');